CREATE DATABASE LIBRARY;
USE LIBRARY;
CREATE TABLE USER_INFO(
ID INT AUTO_INCREMENT NOT NULL,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
EMAIL VARCHAR(50),
ADDRESS VARCHAR(50),
POSTCODE VARCHAR (10),
PRIMARY KEY (ID)
);
CREATE TABLE BOOK_INFO(
BOOK_ID INT AUTO_INCREMENT NOT NULL,
AUTHUR VARCHAR (20),
TITLE VARCHAR (20),
GENRE VARCHAR(10),
PRIMARY KEY (BOOK_ID)
);
CREATE TABLE LOAN_LOG(
BOOK_ID INT,
CUST_ID INT, 
DATE_OUT INT,
RETURNED VARCHAR (3),
FOREIGN KEY (BOOK_ID) REFERENCES BOOK_INFO(BOOK_ID),
FOREIGN KEY (CUST_ID) REFERENCES USER_INFO(ID)
);
INSERT INTO USER_INFO VALUES (1, "POTTER", "HARRY", "H.POTTER@HOGWARTS.COM", "4 PRIVET DRIVE", "HW98 7T");
INSERT INTO USER_INFO VALUES (2, "GRANGER", "HERMIONE", "H.GRANGER@HOGWARTS.COM", "6 ROSE CLOSE", "HW05 8H");
INSERT INTO USER_INFO VALUES (3, "WEASLEY",	"RON", "R.WEASLEY@HOGWARTS.COM", "15 GODRICKS HOLLOW","HW09 7H");
INSERT INTO USER_INFO VALUES (4,"MALFOY","DRACO","D.MALFOY@HOTMAIL.COM","19 DIAGON ALLEY","HW22 7H");
INSERT INTO BOOK_INFO VALUES (1, "FANTASTICAL BEASTS","S.JONES","FICTION");
INSERT INTO BOOK_INFO VALUES (2,"POTION MAKING","K.LEWIS","FICTION");
INSERT INTO BOOK_INFO VALUES (3,"THE DARK ARTS","G.LOCKHEART","FICTION");
INSERT INTO BOOK_INFO VALUES (4, "HERBOLOGY  101","P.SPROUT","FICTION");
INSERT INTO LOAN_LOG VALUES (4, 2, 26/03/2022, NULL);
INSERT INTO LOAN_LOG VALUES (3, 1, 26/03/2022, NULL);
USE LIBRARY;
USE LOAN_LOG;

